### ISSUE TITLE
Set up a basic CI that would simply build the library

### ISSUE THREAD

**Issue by Russoul** [idris-community/LSP-lib#2]

**Comment by phijor** [comment]
Since this project already has a Nix flake, a simple CI could be set up using Determinate Systems' [Magic Nix Cache Action](https://github.com/DeterminateSystems/magic-nix-cache-action):

```yaml
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build LSP-lib with Nix
        run: nix build .
```
